import{i as L,S as $}from"./assets/vendor-5b791d57.js";(function(){const l=document.createElement("link").relList;if(l&&l.supports&&l.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&o(i)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function o(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();document.addEventListener("DOMContentLoaded",()=>{const f=document.querySelector(".form"),l=document.querySelector(".gallery"),n=document.querySelector(".loader"),o=document.querySelector(".button-2"),e=document.querySelector(".end-message");let t=1,i="";f.addEventListener("submit",E),o==null||o.addEventListener("click",b);async function E(r){if(r.preventDefault(),i=r.target.elements.query.value.trim(),i==="")return L.error({message:"Введіть вірне значення!",position:"topRight"});n.style.display="inline-block";try{t=1,l.innerHTML="",await h(i,t),p()}catch(s){console.error("Error:",s)}finally{n.style.display="none"}r.target.reset()}async function b(){n.style.display="inline-block";try{t+=1,await h(i,t),p()}catch(r){console.error("Error:",r)}finally{n.style.display="none"}}async function h(r,s){const a="https://pixabay.com/api/",u="?key=42272316-28c697ce0580eb37211383c7d",c=`&q=${r}`,y="&image_type=photo",g="&orientation=horizontal",A="&safesearch=true",O="&per_page=15",P=`&page=${s}`,R=a+u+c+y+g+A+O+P;try{const m=await fetch(R);if(!m.ok)throw new Error("Network response was not ok");const d=await m.json();d&&d.hits&&d.hits.length>0?(S(d),I(d.totalHits,s)):(L.error({message:"No images found.",position:"topRight"}),q(),o==null||o.classList.add("hidden"),e.classList.remove("hidden"))}catch(m){throw m}}function S(r){const s=r.hits.map(w).join("");l.insertAdjacentHTML("beforeend",s),document.querySelectorAll(".gallery-link").forEach(c=>{c.setAttribute("href",c.querySelector("img").getAttribute("src"))}),new $(".gallery a",{captionsData:"alt",captionDelay:250}).refresh()}function w({largeImageURL:r,webformatURL:s,tags:a,likes:u,views:c,comments:y,downloads:g}){return`<li class="gallery-item">
      <a class="gallery-link" href="${r}">
        <img class="gallery-image" src="${s}" alt="${a}" />
      </a>
      <div class="item-text">
        <ul>Likes<li>${u}</li></ul>
        <ul>Views<li>${c}</li></ul>
        <ul>Comments<li>${y}</li></ul>
        <ul>Downloads<li>${g}</li></ul>
      </div>
    </li>`}function I(r,s){const a=Math.ceil(r/15);s>=a?(o.classList.add("hidden"),e.classList.remove("hidden")):(o.classList.remove("hidden"),e.classList.add("hidden"))}const q=()=>n.style.display="none";function p(){const r=v();window.scrollBy({top:r*2,behavior:"smooth"})}function v(){return document.querySelector(".gallery-item").getBoundingClientRect().height}});
//# sourceMappingURL=commonHelpers.js.map
